// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP3._11dotnetweb.DAL;

#nullable disable

namespace TP3._11dotnetweb.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240922033957_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("TP3._11dotnetweb.Models.Passaporte", b =>
                {
                    b.Property<int>("PassaporteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("PassaporteId");

                    b.ToTable("Passaportes");
                });

            modelBuilder.Entity("TP3._11dotnetweb.Models.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PessoaId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("TP3._11dotnetweb.Models.Passaporte", b =>
                {
                    b.HasOne("TP3._11dotnetweb.Models.Pessoa", "Pessoa")
                        .WithOne("Passaporte")
                        .HasForeignKey("TP3._11dotnetweb.Models.Passaporte", "PassaporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("TP3._11dotnetweb.Models.Pessoa", b =>
                {
                    b.Navigation("Passaporte")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
